bundler/bundler-api

- lib/bundler_api/web.rb
Let's timeout long SQL queries, so it doesn't affect the apps.
> set pg statement_timeout to 1 second

- lib/bundler_api/dep_calc.rb
me and @andremedeiros paired on this query.
It should be equivalent to the old one, but faster, and simpler to understand.
Before: http://explain.depesz.com/s/OdI
After: http://explain.depesz.com/s/g1n
The explanation of why this is faster is that before there was 2 joins on versions, the internal query and the external. Now we only have 1 query.
review @andremedeiros @hone @indirect @dwradcliffe
> Better fetch_dependency query

- lib/bundler_api/web.rb
As discussed with @andremedeiros
> Make sure gems paramter include uniq gems

- Gemfile
- Gemfile.lock
until https://github.com/eric/metriks-librato_metrics/pull/4 gets merged.
> use arthurnn/metriks-librato_metrics for now

- lib/bundler_api/web.rb
> Add hit/miss librato stats for memcached

- lib/bundler_api/web.rb
> [Web] Support RANGE headers on ETag responses

- Gemfile.lock
- lib/bundler_api/agent_reporting.rb
- spec/agent_reporting_spec.rb
> Fix version reporting

- Gemfile
- Gemfile.lock
- db/migrations/07_add_checksum_to_versions.rb
- lib/bundler_api/gem_helper.rb
- lib/bundler_api/gem_info.rb
- lib/bundler_api/update/gem_db_helper.rb
- lib/bundler_api/update/job.rb
- lib/bundler_api/web.rb
- spec/gem_info_spec.rb
- spec/spec_helper.rb
- spec/support/etag.rb
- spec/support/gem_builder.rb
- spec/update/gem_db_helper_spec.rb
- spec/versions_file_spec.rb
- spec/web_spec.rb
This is a draft for adding the required ruby and rubygems to the info response. Check comments inline
> Add required ruby and rubygems versions to /info/gemname

- Gemfile
- Gemfile.lock
- lib/bundler_api/gem_info.rb
- spec/web_spec.rb
Change on the interface - number and platform are sent separated
to the index call
> Change compact_index to version 0.6.0

- Gemfile
- Gemfile.lock
- lib/bundler_api/gem_info.rb
- lib/bundler_api/update/gem_db_helper.rb
- script/integration/migrate.rb
- script/integration/test.rb
- spec/gem_info_spec.rb
- spec/web_spec.rb
This one is a bit more organized than the chaotic #98. You should consider merging this instead.
To make this PR I did a `git diff add_info_checksum` from the `new_index_format` branch, and applied with `patch -p1`, then `git patch -p` the files spliting in logical commits. Also moved the scripts that can be discarted after the migration to a new folder.
> New index checksums

- lib/bundler_api/strategy.rb
- spec/web_spec.rb
@indirect This is a fix for a bug that is in mainline.
A fix of 2 lines that are plain wrong, my bad.
> Fix redirection strategy, symbol instead of the actual id

- Rakefile
- db/migrations/10_add_yanked_at_to_versions.rb
- lib/bundler_api/gem_info.rb
- lib/bundler_api/web.rb
- spec/gem_info_spec.rb
- spec/support/gem_builder.rb
- spec/web_spec.rb
So, this include yanked gems on the dynamic response by pre-pending it with the "-". It also include some missing tests.
Do not merge this yet.
> Deal with yanked gems on compact index

- .travis.yml
- script/setup
If the postgresql server was not the same as the app running, it just failed silently.
I modified the `script/setup` in order to parse the environment variable `DATABASE_URL`  and connect to the db server correctly.
> support setting up the database on another host

- Rakefile
- lib/bundler_api/update/fix_dep_job.rb
- lib/bundler_api/update/gem_db_helper.rb
- lib/bundler_api/update/job.rb
- spec/update/fix_dep_job_spec.rb
- spec/update/gem_db_helper_spec.rb
> Consolidate Job and FixDepJob

- lib/bundler_api/gem_info.rb
Will fix ties such as https://www.dropbox.com/s/lc2eiw9pj9nuxf9/Screenshot%202016-01-22%2019.24.19.png?dl=0
\c @andremedeiros @indirect @fotanus
> [GemInfo] Ensure sorting in versions is stable

- lib/bundler_api/update/gem_db_helper.rb
\c @indirect @dwradcliffe @andremedeiros
> [GemHelper] Ensure synchronized code is run even without a mutex

- lib/bundler_api/update/gem_db_helper.rb
- spec/update/gem_db_helper_spec.rb
> [GemDBHelper] Retry when db connection error

- lib/bundler_api/cache.rb
- lib/bundler_api/web.rb
> [Cache] Purge new index files

- lib/bundler_api/web.rb
This reverts commit 5de9b940273fd931e6bcdf22d4f8f97ff7c2c42c.
> Revert "404 on info endpoint for now"

- lib/bundler_api/cache.rb
@arthurnn @indirect @segiddins
> switch to memcached cloud

- lib/bundler_api/web.rb
\c @dwradcliffe @arthurnn @indirect
> [Web] Add a disable env var for the new index

- spec/web_spec.rb
Tests were not doing what they said they were.
> Fix test name and test response exhaustively

- lib/bundler_api/cache.rb
/cc @segiddins @dwradcliffe @arthurnn
> Remove memcached 15m expiration

- lib/bundler_api/gem_info.rb
- lib/bundler_api/web.rb
- spec/gem_info_spec.rb
- Web#get_deps and Web#deps_for are unused
- GemInfo#deps_for only takes one gem name
> Cleanup deps_for methods

- lib/bundler_api/cache.rb
- lib/bundler_api/web.rb
@indirect @arthurnn @dwradcliffe
> Revert the Reverts

- lib/bundler_api/cache.rb
\c @dwradcliffe @indirect would appreciate a quick r on this, so we can track down why purges are failing
> [Cache] Raise when purging fails

- Gemfile
- Gemfile.lock
- lib/bundler_api/web.rb
> Use Appsignal.send_exception in #in_background

- Gemfile
- Gemfile.lock
- lib/bundler_api/web.rb
Reverts bundler/bundler-api#157
This broke things in config.ru, that's a project for another day
> Revert "Use Appsignal.send_exception in #in_background"

- lib/bundler_api/cache.rb
> Purge memcached before fastly

- lib/bundler_api/cache.rb
> [Cache] Dont try and compare a string to a number

- Rakefile
Ought to fix https://papertrailapp.com/groups/435404/events?q=program%3Aapp%2Fscheduler.5324
\c @indirect
> [Rakefile] Fix purging yanked gems

- Rakefile
Maybe this works?
¯\\\_(ツ)\_/¯
Hard to know since I can't figure out how to run this locally and it's obviously untested since it's in the makefile
\c @indirect
> [Rakefile] Cant update on a join

- Rakefile
Joins are hard!
Manually verified this works. So sorry for all the noise / failures!
> Actually fix yanking

- db/migrations/11_add_yanked_info_checksum_to_versions.rb
- lib/bundler_api/gem_info.rb
- lib/bundler_api/update/gem_db_helper.rb
- lib/bundler_api/web.rb
- spec/gem_info_spec.rb
- spec/support/gem_builder.rb
- spec/web_spec.rb
> Separate yanked_info_checksum for yanked versions

- lib/bundler_api/cache.rb
- lib/bundler_api/web.rb
- spec/cache_spec.rb
- spec/update/job_spec.rb
I am not sure if this is what was needed in #141 Still, here goes nothing
> Use memcache for new index response

- README.md
> [README] Add deprecation notice
