bundler/bundler-api

lib/bundler_api/web.rb, spec/web_spec.rb
This will severely decrease the timeout errors we've been having. 
From what I could tell, it seems that someone is using a hacked version of Bundler (by removing the gem limit), which in turn times out our API and breaks it for a small period of time for everyone else.
=> Limit gem dependency requests to 100 gems.

lib/bundler_api/metriks.rb
As far as we can tell, metriks-librato_metrics is failing to send data,
and it never cleans the data.
We are getting errors like:
LibratoMetrics: Broken pipe
on the logs, but without any stacktrace. With a trace we can know better
why the pipe is broken.
=> Print backtrace on librato error.

lib/bundler_api/agent_reporting.rb
Maybe I am missing something, but as far as I can tell `rescue ex` wont work. see a small test https://gist.github.com/arthurnn/ff127c64591953768144 .
cheers.
review @andremedeiros
=> Fix rescue syntax

lib/bundler_api/cache.rb
Not sure how, but we are getting some gem cache out-of-sync.
Probably some race condition, or a something else.
If we add a ttl, it will fix the issue, even if that doesnt make me happy.
We can play if the TTL, after we deploy this, we can watch the number of cache miss,
and lower or increase this number
=> Add default ttl, 15 min to gem cache

lib/bundler_api/agent_reporting.rb, spec/agent_reporting_spec.rb
This patch is a complement from the new information sent by bundler on the user agent. It add a new metrik that keep track of how often different CIs run bundler commands.
=> Keep track of which CI run a command if any

Rakefile
Sorry, forgot to remove this on last patch. I'm not sure how this passed the tests.
=> Remove require for inexistent file

Gemfile, Gemfile.lock, lib/bundler_api/web.rb
The response body is also shared by rubygems.org and bundler-api. So it
is natural to move this code to compact-index gem.
This patch does not remove the spec format response. I think it is
healty to keep some basic test on the response format as well, so we can
do more complete tests on the compact-index itself.
Thoughts?
=> Move response bodies to compact_index gem

Gemfile, Gemfile.lock, lib/bundler_api/gem_info.rb
This updates the compact index to lastest and uses the structs, which should be faster than the hashes.
=> Use compact index structures instead of hashes

lib/bundler_api/metriks.rb
After a fresh checkout, I ran script/setup which didn't give any errors, so I ran script/web to start the server. It gave 2 errors, which this PR fixes. After I made this patch, it all started fine and seems to work ok.
The errors I got:
```sh
~/ws/bundler-api/lib/bundler_api/metriks.rb:8:in `start': undefined method `new' for BundlerApi::Metriks:Module (NoMethodError)
from puma.rb:6:in `_load_from'
from ~/.rvm/gems/ruby-2.2.2/gems/puma-2.11.3/lib/puma/dsl.rb:20:in `instance_eval'
```
```sh
~/ws/bundler-api/lib/bundler_api/metriks.rb:8:in `start': undefined method `start' for #<BundlerApi::Metriks:0x00000002459fc8> (NoMethodError)
from puma.rb:6:in `_load_from'
from ~/.rvm/gems/ruby-2.2.2/gems/puma-2.11.3/lib/puma/dsl.rb:20:in `instance_eval'
```
I did the most straightforward fix for …
=> Fixes so script/web works

lib/bundler_api/strategy.rb, lib/bundler_api/web.rb
This is a RFC which opens the door for changing what do the server does when a gem (or any other URL) is requested, for now this is simply extracting the redirection strategy that is already embedded in the app into an object that does exactly that: redirect to rubygems.
The way to continue from here is creating a caching strategy object that will have a storage of some kind, (probably just a local storage on a folder). On request, this object will first search for the file in this local storage, if it finds it, it will just serve it with the caching file and http headers; else it will pull the file to make a local cache.
The way of caching a file is simply using some smart enough http object like Faraday, pull the file following redirects (as rubygems redirects to S3), and store both the …
=> Extract redirect strategy

script/setup
When I ran script/setup on a machine that didn't have postgresql (but it did have postgres dev libs apparently, as the pg gem installed without problem), I get the following error:
```sh
$ script/setup
Creating database
~/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/open3.rb:193:in `spawn': No such file or directory - createdb (Errno::ENOENT)
from ~/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/open3.rb:193:in `popen_run'
from ~/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/open3.rb:188:in `popen2e'
from ~/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/open3.rb:335:in `capture2e'
from script/setup:53:in `<main>'
```
When I ran script/setup on my other machine that had postgresql set up, but not memcached, the server set up fine, ran fine, but the specs failed until I installed memcached.
It seems like some dependency …
=> Check dependencies before setting up

.env, Rakefile, lib/bundler_api/gem_helper.rb
(instead of old hardcoded s3 bucket)
This is already running in production via heroku config variable.
@indirect @andremedeiros @evanphx
=> update download url to use fastly

Gemfile, Gemfile.lock
I am suspecting that https://github.com/indirect/dalli/commit/4be6be64e643eaaef76310ad6e67ffef8ce32980 could be causing slow multi_gets in memcached
=> use dalli stable

Gemfile, Gemfile.lock, lib/bundler_api/cache.rb, spec/spec_helper.rb
I mentioned the other day that the [memcached](https://github.com/arthurnn/memcached) gem is faster than Dalli, specially on multi_get, this is the latest 2.0 benchmarks on multi_get, compared with dalli.
```
get-multi: dalli:bin                   8.400000   3.700000  12.100000 ( 12.739551)
get-multi: libm:ascii                  0.990000   1.260000   2.250000 (  3.418817)
get-multi: libm:ascii:pipeline         1.000000   1.270000   2.270000 (  3.425416)
get-multi: libm:ascii:udp              0.900000   0.720000   1.620000 (  1.910331)
get-multi: libm:bin                    1.160000   2.580000   3.740000 (  5.758965)
get-multi: libm:bin:buffer             1.190000   2.660000   3.850000 (  5.901414)
```
WARNING:  this memcached version is not been used in production yet. However all tests …
=> Use memcached instead of Dalli

Gemfile, Gemfile.lock, lib/bundler_api/cache.rb, spec/spec_helper.rb
This reverts commit 4f6bc538d51a0139da7e5a9fb89be47158991a1e, reversing
changes made to 8af966db029364911288a0e03224b92ecbeec298.
Had to revert this. To install it, it needs libsasl, which is not
available on heroku
=> Revert "Merge pull request #150 from bundler/arthurnn/memcached_gem"

Gemfile, Gemfile.lock, Rakefile
It's unused since 4097dfd4645fea8511e10f3cc1b7bde9e4c1db5b .
=> Remove lock-smith gem

lib/bundler_api/web.rb
Fixes the issues caused by https://github.com/bundler/bundler-api/pull/156 :(
This way, if purging fastly fails for purging the specs, at least
memcached will be purged for the dependency API. Finishes up https://github.com/bundler/bundler-api/pull/160.
Add exception only will add the exception to the current appsignal
transaction. If there is no transaction, I think that means we never get
the exception. Sending it actually sends it.
=> Purge gem before purging specs

lib/bundler_api/cache.rb, lib/bundler_api/web.rb, spec/cache_spec.rb
This ensures we can use the full_name to purge the .gem and the .gemspec and only the name for memcache and the info endpoint
\c @indirect @dwradcliffe
=> Purge a gem with its gem_helper 

Rakefile
I already did the Fastly configuration to make the wildcard purge work, but the wildcard requires that we do one last purge all before the surrogate keys will be tagged correctly so we can purge them together.
/cc @segiddins @dwradcliffe
=> Add rake task to purge compact index from Fastly

lib/bundler_api/web.rb
By doing this, we can at least be sure that gem pushes will show up in the compact index within 60 minutes, even if we somehow miss the webhook from rubygems.org or the Fastly purge request fails to send. (For example, this would have fixed bundler/bundler#4495 without any human intervention.)
=> Drop Fastly cache time to 1 hour

lib/bundler_api/metriks.rb
=> Add comma after the last item of a multiline hash

Rakefile, lib/bundler_api/update/job.rb
Run example:
```
Finished Enqueuing Jobs!
Adding: repres-bootstrap-1.0.3
Purging /quick/Marshal.4.8/repres-bootstrap-1.0.3.gemspec.rz, /gems/repres-bootstrap-1.0.3.gem, /info/repres-bootstrap
Adding: repres-react-1.0.4
Purging /quick/Marshal.4.8/repres-react-1.0.4.gemspec.rz, /gems/repres-react-1.0.4.gem, /info/repres-react
```
=> Purge gem cache directly in BundlerApi::Job

Rakefile
```
{:name=>"jekyll-multiple-lang", :version=>"1.0.1"}
Connecting to database with up to 1 connections... connected!
rake aborted!
NameError: undefined local variable or method `version' for main:Object
/home/ubuntu/www/bundler-api/Rakefile:241:in `block in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/home/ubuntu/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```
=> Fix rake yank_spec
